export enum constants {
    CHECK_AUTH = 'CHECK_AUTH',
    AUTH_START = 'AUTH_START',
    AUTH_FAILED = 'AUTH_FAILED',
    AUTH_SUCCESS = 'AUTH_SUCCESS',
    RESET_AUTH_MESSAGES = 'RESET_AUTH_MESSAGES'
}