
export enum constants {
    FIX_MIDDLE_BAR = 'FIXED_MIDDLE_BAR',
    UNFIX_MIDDLE_BAR = 'UNFIX_MIDDLE_BAR',
    SEARCH_PRODUCTS_START = 'SEARCH_PRODUCTS_START',
    SEARCH_PRODUCTS_SUCCESS = 'SEARCH_PRODUCTS_SUCCESS',
    RESET_SEARCHED_PRODUCTS = 'RESET_SEARCHED_PRODUCTS',
    LOAD_MORE_PRODUCTS_START = 'LOAD_MORE_PRODUCTS_START',
    LOAD_MORE_PRODUCTS_SUCCESS = 'LOAD_MORE_PRODUCTS_SUCCESS'
}